import { v4 as uuidv4 } from "uuid"; 

function chillHop() {
    return [

        {
            name:"Houston Blues Radio",
            artist: "HoustonBluesRadio",
            cover: "https://img.freepik.com/vector-gratis/fondo-noticias-tecnologia-tierra-digital_1017-36675.jpg",
            id: uuidv4(),
            color: ["#F24933", "#F9B437"],
            audio: "https://ais-sa5.cdnstream1.com/b76353_128mp3",
            active: true,
        },
        {
            name:"113.FM Blues Town",
            artist: "113.FMBluesTown",
            cover: "https://img.freepik.com/foto-gratis/microfono-moderno_144627-41311.jpg",
            id: uuidv4(),
            color: ["#D7B0D5", "#CBDFE0"],
            audio: "https://113fm-atunwadigital.streamguys1.com/1005",
            active: false,
        },
        {
            name:"The Blues Guitar Place",
            artist: "TheBluesGuitarPlace",
            cover: "https://cdn-icons-png.flaticon.com/512/1251/1251671.png",
            id: uuidv4(),
            color: ["#1D2731", "#F17E76"],
            audio: "https://login.webinternetradio.com/blueguitar",
            active: false,
        },
        {
            name:"TOPBLUES",
            artist: "TOPBLUES",
            cover: "https://img.freepik.com/vector-gratis/fondo-onda-ecualizador-colorido_52683-33072.jpg",
            id: uuidv4(),
            color: ["#008781", "#cfc08c"],
            audio: "https://us3.internet-radio.com/proxy/topblues?mp=/stream&1624370498215",
            active: false,
        },
        {
            name:"Blues Café Radio",
            artist: "BluesCaféRadio",
            cover: "https://img.freepik.com/vector-gratis/iconos-banderas_1010-531.jpg",
            id: uuidv4(),
            color: ["#845648","#FDFBDF"],
            audio: "https://manager4.streamradio.fr:2445/stream",
            active: false,
        },
        {
            name:"Radio Eure du Blues",
            artist: "RadioEureduBlues",
            cover: "https://img.freepik.com/vector-gratis/fondo-onda-ecualizador-colorido_52683-33072.jpg",
            id: uuidv4(),
            color: ["#578CCE", "#E9D6D0"],
            audio: "https://stream.rcast.net/65263",
            active: false,
        },
        {
            name:"RJM Radio JAZZY",
            artist: "RJMRadioJAZZY",
            cover: "https://img.freepik.com/vector-gratis/fondo-retro-dia-mundial-radio_23-2147594195.jpg",
            id: uuidv4(),
            color: ["#191516", "#82698E"],
            audio: "https://listen.radioking.com/radio/127546/stream/167344",
            active: false,
        },
        {
            name:"ABC Relax",
            artist: "ABCRelax",
            cover: "https://img.freepik.com/foto-gratis/dispositivo-digital-inalambrico-auriculares-rosa_53876-96804.jpg",
            id: uuidv4(),
            color: ["#7BC8DD", "#D64A59"],
            audio: "https://manager7.streamradio.fr/abcrelax",
            active: false,
        },
        {
            name:"Blues",
            artist: "Blues",
            cover: "https://img.freepik.com/vector-gratis/tierra-lineas-red_1017-8010.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://bluesserver.rock-radio.uk/stream",
            active: false,
        },
        {
            name:"DIMENSIONE JAZZ",
            artist: "DIMENSIONEJAZZ",
            cover: "https://img.freepik.com/vector-gratis/texto-plano-dia-mundial-radio_23-2148825802.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://mpc1.mediacp.eu/stream/dimensionejazz",
            active: false,
        },
        {
            name:"Blue Italia",
            artist: "BlueItalia",
            cover: "https://img.freepik.com/vector-gratis/marco-neon-vivo-aire_23-2148758076.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://bluesitalia.stream.laut.fm/bluesitalia",
            active: false,
         },
         {
            name:"Bluesstation4you",
            artist: "Bluesstation4you",
            cover: "https://img.freepik.com/vector-gratis/dia-mundial-radio-diseno-plano_23-2148802732.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://bluesstation4you.stream.laut.fm/bluesstation4you",
            active: false,
         },
         {
            name:"LeseWoche",
            artist: "LeseWoche",
            cover: "https://img.freepik.com/vector-gratis/radio-plana-retro-ilustrada_23-2148812864.jpg",
            id: uuidv4(),
            color: ["#FDE1A9", "#A46874"],
            audio: "https://lesewoche.stream.laut.fm/lesewoche",
            active: false,
        },
    ];
}

export default chillHop;


